// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.PlaceholderTextGenerator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("paragraphs")]
        public string[] Paragraphs { get; set; }

        [JsonProperty("paragraph_count")]
        public long ParagraphCount { get; set; }

        [JsonProperty("sentences_per_paragraph")]
        public long SentencesPerParagraph { get; set; }

        [JsonProperty("total_sentences")]
        public long TotalSentences { get; set; }

        [JsonProperty("total_words")]
        public long TotalWords { get; set; }

        [JsonProperty("total_characters")]
        public long TotalCharacters { get; set; }

        [JsonProperty("full_text")]
        public string FullText { get; set; }

        [JsonProperty("available_styles")]
        public string[] AvailableStyles { get; set; }
    }
}
